In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [7]:
class SimpleMLP(nn.Module):
    def __init__(self):
        super().__init__()
        # 定义最简单的MLP结构：输入层 -> 隐藏层 -> 输出层
        self.fc1 = nn.Linear(4, 2)  # 输入4个特征，隐藏层8个神经元
        #  在PyTorch的 nn.Linear中，权重矩阵的形状是 [out_features, in_features]
        self.fc2 = nn.Linear(2, 2)   # 输出2个类别
        # 可以添加一个简单的激活函数
        self.relu = nn.ReLU()
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

In [8]:
 class SimpleMLP(nn.module):
        def __init__(self):
            super().__init__()
            self.model = nn.Sequential(
                    nn.Linear(4, 2),
                    nn.ReLU(),
                    nn.Linear(2,2))
            
            
        def forward(self, x):
            x=self.model(x)
            return x

AttributeError: module 'torch.nn' has no attribute 'module'

In [3]:
model = SimpleMLP()
print(model)

SimpleMLP(
  (fc1): Linear(in_features=4, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=2, bias=True)
  (relu): ReLU()
)


In [4]:
total_params = 0
trainable_params = 0

for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"参数名: {name}")
        print(f"参数形状: {param.shape}")
        print(f"参数数量: {param.numel()}")
        print(f"参数值:\n{param.data}")
        print("-" * 30)
        total_params += param.numel()
        trainable_params += param.numel()

参数名: fc1.weight
参数形状: torch.Size([2, 4])
参数数量: 8
参数值:
tensor([[ 0.2870,  0.2311, -0.4584,  0.1737],
        [ 0.0013,  0.0104,  0.1118, -0.1931]])
------------------------------
参数名: fc1.bias
参数形状: torch.Size([2])
参数数量: 2
参数值:
tensor([0.3481, 0.1269])
------------------------------
参数名: fc2.weight
参数形状: torch.Size([2, 2])
参数数量: 4
参数值:
tensor([[ 0.6538, -0.5546],
        [ 0.4082,  0.2238]])
------------------------------
参数名: fc2.bias
参数形状: torch.Size([2])
参数数量: 2
参数值:
tensor([ 0.7025, -0.4155])
------------------------------


In [6]:
test_input = torch.randn(3, 4)
y = model(test_input)
print(y)

tensor([[ 0.9505, -0.2606],
        [ 1.2390, -0.0805],
        [ 0.5242, -0.3436]], grad_fn=<AddmmBackward0>)
